feat: make oob_ip available regardless of oob_ip_as_primary_ip
netbox-community/ansible_modules pull request #1211
Opened 2024-04-15 17:45 UTC by akire0ne

## Related Issue

N/A

## New Behavior

Related to https://github.com/netbox-community/ansible_modules/pull/1081

Makes `oob_ip` always available in the hostvars if it exists.

## Discussion: Benefits and Drawbacks

Not sure why we don't make `oob_ip` available only when `oob_ip_as_primary_ip` is set.

I believe there is value to access this property without altering `ansible_host` value.

## Changes to the Documentation

None

## Proposed Release Note Entry

- oob_ip is now returned in hostvars if set
- Add the ability to set out of band IP as ansible host.

## Double Check

* [ ] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [ ] I have explained my PR according to the information in the comments or in a linked issue.
* [ ] My PR targets the `devel` branch.

2024-04-15 21:10 UTC, sc68cal commented
@Shourai can you please take a look, since you implemented the original feature?

2024-04-16 10:02 UTC, Shourai commented
I have checked it out and tested it.
It's a really nice solution.

- With `oob_ip_as_primary_ip: false` and oob_ip defined but primary ip undefined, the variable `oob_ip` will be available but `ansible_host` will not be.

- With `oob_ip_as_primary_ip: true` and oob_ip defined but primary ip undefined, the variable `oob_ip` will be available and `ansible_host` will also be available.

It's useful if you have `oob_ip` defined and want to use that variable but not overwrite the `primary_ip` as `ansible_host`.

2024-04-16 18:21 UTC, sc68cal commented
That is a large matrix of behaviors. I don't know if I am a fan of this change.

2024-04-16 18:25 UTC, sc68cal commented
Frankly I would rather have one configuration setting, where you either use the `primary_ip` of a device, or the `oob_ip` of a device, and leave it at that.

2024-04-16 18:27 UTC, sc68cal requested changes
Creates too complex behaviors

2024-04-16 18:56 UTC, akire0ne commented
Folks, two different things here
- `oob_ip` is displayed on the Device UI in the same manner as `Primary IPv4` and `Primary IPv6` - So for me I would expect to be displayed in my hostvars, in the same fashion as `primary_ip4` and `primary_ip6`are.
- Ability to set `oob_ip` as a `ansible_host` - We don't have that need, but as @Shourai already implemented something with `oob_ip` so I didn't wanted to clash with this.

Whatever works for me as long `oob_ip` is available when set on the device. 

@sc68cal are you suggesting something like an `ansible_host_ip_source` setting, which could be set to either `primary_ip4` (default) or `oob_ip` ? 

FYI our business case is to be able to fetch / identify OOBM / IPMI easily for our devices.

2024-04-17 21:59 UTC, sc68cal approved these changes
OK. It took me a couple reads through your comments @akire0ne and @Shourai, because for some reason my brain was just not working properly and I was getting confused.

It was not because of anything you wrote, but for some reason it just didn't stick with me for some reason. 

It's sad because the code is quite clear what is going on but I just wasn't getting it. Sorry. 

This is good to go, thank you for the contribution and your patience, I will try and do better next time.

2024-04-17 22:00 UTC, merged

2024-04-18 12:40 UTC, akire0ne commented
Thanks @sc68cal  ! Very appreciated