Bugfix: nb_inventory.py group_by: tags (NB 2.9+)
netbox-community/ansible_modules pull request #340
Opened 2020-09-22 14:59 UTC by jkuzma07

Fixes #287. Code stolen from @dotSource-GmbH.
Made a mess of some authorship revisions on the #333 fork. Starting fresh.

2020-09-27 03:00 UTC, FragmentedPacket requested changes

2020-09-27 17:12 UTC, jkuzma07 commented on plugins/inventory/nb_inventory.py
> +            return []
Saves memory and returns the same data? I like it.

2020-09-27 17:28 UTC, merged

2020-10-06 21:50 UTC, FragmentedPacket commented
It's probably just all the stuff from Ansible 2.10 and NB2.9 changes.

I'm trying to true up all the testing before cutting a new release for things that made it through without testing

2020-10-15 05:35 UTC, MaartenMol commented
@FragmentedPacket if I make the local changes like above code, do I have a working workaround?

2020-10-16 02:16 UTC, FragmentedPacket commented
@MaartenMol Yes it should. I believe I cut 1.1.0 that has this fix in it as well.

You can install from galaxy or build and install locally