This adds many missing API endpoints - fixes #641
netbox-community/ansible_modules pull request #655
Opened 2021-11-18 03:06 UTC by ThomasADavis

Fixes issue #641

It include endpoints for v3.1

No depecrated API endpoints have been removed.

2021-11-18 18:27 UTC, sc68cal requested changes

2021-11-18 18:27 UTC, sc68cal commented on plugins/lookup/nb_lookup.py
> +        # "wireless-lan-groups": {"endpoint": netbox.wireless.wireless_lan_groups},
Do not add this to a changeset if you are going to leave it commented out, IMO.

2021-11-22 18:58 UTC, rodvand commented
How about you just add missing endpoints, and leave out the 3.1 endpoints for now? And then when 3.1 is released we'll cut a specific release where we add 3.1 stuff? As you mentioned in another issue we also have to wait for a pynetbox to support some of the endpoints.

2021-11-22 19:35 UTC, ThomasADavis commented
I'm thinking of this:

```
    try:
        netbox_endpoint_map["wireless-lan-groups"] = {"endpoint": netbox.wireless.wireless_lan_groups}
        netbox_endpoint_map["wireless-lan-groups"] = {"endpoint": netbox.wireless.wireless_lan_groups}
        netbox_endpoint_map["wireless-lan"] = {"endpoint": netbox.wireless.wireless_lan}
        netbox_endpoint_map["wireless-links"] = {"endpoint": netbox.wireless.wireless_links}

    except AttributeError as e:
        Display().v(u"no wireless API support, please update your pynetbox.")

```
so it will still work on older versions of pynetbox.

2021-11-24 18:20 UTC, sc68cal approved these changes
looks good to me

2021-11-24 18:49 UTC, ThomasADavis commented
The wireless api can't be added until widespread acceptance of an updated pynetbox is available..which means when they get added, it could break many ansible installations.  For me, widespread acceptance means when a distribution like Centos8 streamCentos8/RHEL8/RHEL9,  Fedora ships the updated pynetbox as an RPM. We tried a python venv environment for a year, and the issues was numerous (starting with python it self)

Using the try/exception avoids that problem.

2021-11-27 12:08 UTC, rodvand commented
I can see how we would need some logic to deal with new endpoints with NetBox 3.1. I guess it has just been so long since the endpoints have changed it hasn't really been an issue.

2021-11-27 12:08 UTC, merged